[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

# 测试配置
[profile.default.fuzz]
runs = 1000

# 不变性测试配置
[profile.default.invariant]
runs = 1000
depth = 15

# 元数据配置
[profile.default.metadata]
bytecode_hash = "ipfs"

# Gas 报告配置
[profile.default.gas_reports]
"*" = ["*"]

# 网络配置
[profile.default.networks]
hardhat = { type = "edr-simulated", chain_id = 1337 }

# 测试配置
[profile.default.test]
gas_limit = 10000000
gas_price = 0
block_timestamp = 0
block_number = 0
